name: CI/CD Tienda Perritos - DB

on:
  push:
    branches:
      - main
    paths:
      - 'db/**'

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push DB
        uses: docker/build-push-action@v5
        with:
          context: ./db
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tienda-db:latest

      - name: Deploy en EC2 DB
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_DB_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.EC2_HOST }}
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tienda-db:latest
            docker stop tienda-db || true
            docker rm tienda-db || true
            docker run -d --name tienda-db -p 3306:3306 \
              -e MYSQL_ROOT_PASSWORD=admin123 \
              -e MYSQL_DATABASE=tienda_perritos \
              ${{ secrets.DOCKERHUB_USERNAME }}/tienda-db:latest
